# https://docs.docker.com/compose/compose-file/

version: '2'

services:
  zookeeper1:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 1
    ports:
      - "2181:2181"
    networks:
      - back
  zookeeper2:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 2
    networks:
      - back
  zookeeper3:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 3
    networks:
      - back
  zkcli:
    build:
      dockerfile: Dockerfile.zkcli
      context: .
    stdin_open: true
    tty: true
    networks:
      - back

networks:
  back:
    driver: bridge
